#!/usr/bin/env bash
set -eu
source ansible/installer.sh

RUN_SYSTEM=0
RUN_USER=0

# No args, means assume run both user and system migrations.
if [ "$#" -eq 0 ]; then
    RUN_SYSTEM=1
    RUN_USER=1
fi

# Check options.
while getopts "su" opt; do
    case "$opt" in
        s) RUN_SYSTEM=1 ;;
        u) RUN_USER=1 ;;
        *) exit 1 ;;
    esac
done

if [ "$RUN_SYSTEM" -eq 1 ]; then
    sudo --validate
    banner "SYSTEM CHANGES"
    sudo ansible-playbook \
        -c local \
        -i ansible/inventory.ini \
        ansible/system.yml
fi

if [ "$RUN_USER" -eq 1 ]; then
    banner "USER CHANGES"
    ansible-playbook \
        -i ansible/inventory.ini \
        ansible/user.yml
fi
