---
- name: Ensure GPG directory exists.
  ansible.builtin.file:
    path: "{{ user_home }}/.gnupg"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  notify: Restart gpg-agent

- name: Configure GPG agent to use terminal password prompts.
  ansible.builtin.copy:
    content: |
      pinentry-program /usr/bin/pinentry-curses
    dest: "{{ user_home }}/.gnupg/gpg-agent.conf"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  notify: Restart gpg-agent
