---
- name: Link screenrc.
  ansible.builtin.file:
    src: "{{ dotfiles_dist }}/screenrc"
    dest: "{{ user_home }}/.screenrc"
    state: link
    force: true

- name: Link tigrc.
  ansible.builtin.file:
    src: "{{ dotfiles_dist }}/tigrc"
    dest: "{{ user_home }}/.tigrc"
    state: link
    force: true
