---
- name: Configure system-level workstation settings.
  hosts: localhost
  connection: local
  become: true

  roles:
    - geerlingguy.nodejs

  vars:
    dotfiles_root: "{{ playbook_dir }}/.."
    dotfiles_dist: "{{ dotfiles_root }}/dist"
    nodejs_install_npm_user: "{{ ansible_facts['user_id'] }}"
    nodejs_version: "26.x"

  tasks:
    - name: Configure apt packages.
      ansible.builtin.import_tasks: tasks/system/packages.yml

    - name: Configure Vim.
      ansible.builtin.import_tasks: tasks/system/vim.yml

    - name: Configure kernel settings.
      ansible.builtin.import_tasks: tasks/system/kernel.yml

    - name: Install nvm and Node.js.
      ansible.builtin.import_tasks: tasks/system/node.yml
