---
- name: Configure user-level dotfiles and preferences.
  hosts: localhost
  connection: local
  become: false

  vars:
    user_home: "{{ ansible_facts['env']['HOME'] }}"
    dotfiles_root: "{{ playbook_dir }}/.."
    dotfiles_dist: "{{ dotfiles_root }}/dist"

  tasks:
    - name: Configure Vim.
      ansible.builtin.import_tasks: tasks/user/vim.yml

    - name: Configure terminal tools.
      ansible.builtin.import_tasks: tasks/user/terminal.yml

    - name: Configure Git.
      ansible.builtin.import_tasks: tasks/user/git.yml

    - name: Configure Bash.
      ansible.builtin.import_tasks: tasks/user/bash.yml

    - name: Configure SSH.
      ansible.builtin.import_tasks: tasks/user/ssh.yml

    - name: Gather installed package facts.
      ansible.builtin.package_facts:
        manager: auto
      tags:
        - never
        - gnome

    - name: Configure GNOME preferences.
      ansible.builtin.include_tasks:
        file: tasks/gnome.yml
        apply:
          tags:
            - gnome
      when: "'xserver-xorg-core' in ansible_facts.packages"
      tags:
        - never
        - gnome


    - name: Configure npm.
      ansible.builtin.import_tasks: tasks/user/npm.yml

    - name: Configure GPG.
      ansible.builtin.import_tasks: tasks/user/gpg.yml

  handlers:
    - name: Restart gpg-agent
      ansible.builtin.command:
        cmd: gpgconf --kill gpg-agent
