---
- name: Set default editor to Vim.
  ansible.builtin.command:
    cmd: update-alternatives --set editor /usr/bin/vim.basic
  changed_when: false

- name: Ensure root vimrc exists.
  ansible.builtin.copy:
    content: ""
    dest: /root/.vimrc
    force: false
    mode: "0644"
